ignore session2

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -32,12 +32,12 @@ jobs:
           fi
           echo "[🟩] $file ran successfully"
         done
-        cd ../session2
-        for file in $(ls *.py); do
-          python $file
-          if [ $? -ne 0 ]; then
-            echo "[🟥] Error running $file"
-            exit 1
-          fi
-          echo "[🟩] $file ran successfully"
-        done
+        # cd ../session2
+        # for file in $(ls *.py); do
+        #   python $file
+        #   if [ $? -ne 0 ]; then
+        #     echo "[🟥] Error running $file"
+        #     exit 1
+        #   fi
+        #   echo "[🟩] $file ran successfully"
+        # done
